pretrained_model_path: "stabilityai/stable-diffusion-2-depth"
output_dir: "./outputs/pix2video/man-surfing"

train_data:
  video_path: "data/man-surfing.mp4"
  prompt: "a man is surfing"
  n_sample_frames: 16
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 3

validation_data:
  prompts:
    - "a boy is surfing"
    - "Bat man is surfing"
    - "Iron Man is surfing"
    - "Donald Trump is surfing "
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

train_batch_size: 1
seed: 33
mixed_precision: fp16
enable_xformers_memory_efficient_attention: True
